### PR TITLE
Gps elevation correction for GPS files

### PR DESCRIPTION
**Pull request by lbesson**

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Actually, it may happen anywhere in the track : https://www.camptocamp.org/outings/1273855/fr/tour-d-anzeinde-versant-ne-par-anzeinde 

DYT it would be possible to clean them ?

**Comment by lbesson** [comment]
I'll look at it

**Comment by lbesson** [comment]
you can have a look at it

**Comment by cbeauchesne** [comment]
Is it supposed to fix this one ? https://c2corg.github.io/c2c_ui/gps-elevation-correction/#/outings/1273855/fr/tour-d-anzeinde-versant-ne-par-anzeinde

**Comment by lbesson** [comment]
Page not found :/

**Review by cbeauchesne — APPROVED** [review]

**Comment by cbeauchesne** [comment]
ok, let's move forward!

**Pull request merged**
