### PR TITLE
add slovenian lang for ui

### PR DESCRIPTION
**Pull request by AntoineMarnat**
Work in progress: I do not know how to create and get from transifex the sl_Sl.json file

inspired from: https://github.com/c2corg/c2c_ui/pull/2013/files

### CODE REVIEW

**Comment by AntoineMarnat** [comment]
I guess one should add the sl_Sl lang here:

https://github.com/c2corg/c2c_ui/runs/4165031309?check_suite_focus=true

**Comment by AntoineMarnat** [comment]
https://github.com/c2corg/c2c_ui/issues/2334

**Comment by brunobesson** [comment]
I'll take over it. By the way, I'll change the lang on transifex from sl_SI to sl, unless there is a reason not to (no worries, I'll only make a copy for now)? Then I'll let you update rights for translation team?

**Comment by brunobesson** [comment]
Replaced by #2496 
@AntoineMarnat see also commit b7678083b63c219611e2fced6f4cc165df534e54 for adding slovenian to the sync with transifex.

**Comment by AntoineMarnat** [comment]
> I'll take over it. By the way, I'll change the lang on transifex from sl_SI to sl, unless there is a reason not to (no worries, I'll only make a copy for now)? Then I'll let you update rights for translation team?

OK, I guess I was "only" missing that step : https://github.com/c2corg/c2c_ui/commit/b7678083b63c219611e2fced6f4cc165df534e54

I updated the rights of the translation team, should I erase sl_Sl now ? (I think so, but I prefer confirmation!)

**Comment by brunobesson** [comment]
Yes, you can

**Pull request closed without merging**
