### PR TITLE
Lifts and glacier_gears  #457

### PR DESCRIPTION
**Pull request by AntoineMarnat**
I do not know how to put a `<v-translate>` as a value for fields.glacier_gear in `<field-view>`.

### CODE REVIEW

**Review by ataraxido — APPROVED** [review]
Okay for me

**Review by brunobesson — COMMENTED** [review]
For the code part, ok for me. As for the logic, I am a bit more reluctant now after some tests to always display that there is no need for glacier gear for every skitouring or snowshoeing route.
Seing this for Chamechaude, I'm skeptical...

Maybe we should only display it if different from no or not set?

**Comment by AntoineMarnat** [comment]
> For the code part, ok for me. As for the logic, I am a bit more reluctant now after some tests to always display that there is no need for glacier gear for every skitouring or snowshoeing route.
> Seing this for Chamechaude, I'm skeptical...
> 
> Maybe we should only display it if different from no or not set?

I agree. Maybe show "no" and "unknown" (with edit link) wether empty for 'mountain_climbing' and 'snow_ice_mixed' ? Or only snow_ice_mixed ?

**Comment by brunobesson** [comment]
One should open a small discussion on the forum 🥇

**Comment by AntoineMarnat** [comment]
> One should open a small discussion on the forum 🥇

Done:
https://forum.camptocamp.org/t/champ-materiel-glacier/271849

**Comment by AntoineMarnat** [comment]
I feel like a buck eejit, I just did some tests and there is no such thing as a _null_ value for the relevant activities ... 

We may want a default value to be _unkown_, as we may have _no_ value by default that do not reflect the truth - a problem if we show them. New value means API, I guess. Sorry for my misunderstanding 👎 .

**Pull request closed without merging**
