### PR TITLE
fix(reports-fields): remove duplicated default values

### PR DESCRIPTION
**Pull request by joffreyverd**
Linked to the following issue: https://github.com/c2corg/c2c_ui/issues/1332

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Hello @joffreyverd ,

Thank's a lot for your PR! 

Just, You do not need to touch translations files, they are generated automatically from our translation tool. Once we'll removed the property, it'll disappear automatically from those files

Side note, `common.json` is also generated automatically from the API DB model. Theorically, we should not touch it (really sorry, we definitely lack of docs 😞).

We can ship with this hack, but until it's not fixed on API side, we must be carefull to not overwrite this change.

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
Do not touch translations files

**Comment by cbeauchesne** [comment]
oups, sorry, I was not clear enough:  `common.json` even if it's a hack, just keep it that way

**Comment by joffreyverd** [comment]
Sorry for this misunderstanding!

**Review by cbeauchesne — APPROVED** [review]

**Comment by cbeauchesne** [comment]
Thanks @joffreyverd !

**Comment by cbeauchesne** [comment]
Released, thanks @joffreyverd  (btw, we have a developper group on the forum, useful for discussions with camptocamp association, if you're willing to, I can add you, simply give me your forum name).

**Comment by joffreyverd** [comment]
@cbeauchesne here is my forum name: `laManteReligieuse`

**Pull request merged**
