### PR TITLE
Put toolbox at the end of the page on mobile

### PR DESCRIPTION
**Pull request by flob38**
Related to [issue 403, point 4](https://github.com/c2corg/c2c_ui/issues/403).

Maybe it's not the best way to do it.

### CODE REVIEW

**Comment by flob38** [comment]
I didn't search a lot but can't see a way of doing this.
With v-if, I guess we could avoid duplicate the lines in the render (is-hidden-mobile only put display:none) but not in the code.

By the way, I did this on outing, but there are also the others documents to do...
A global solution would be nicer.
I tried some css stuff like `position: absolute` for the toolbox but it's based on the heigth of the page without the scroll.
image

**Comment by flob38** [comment]
The problem with flexbox is that it's complicated to have 2 vertical items (map and toolbox) beside the main content without nested element (and we don't want to if we want to separate map and toolbox on mobile).
float does that well...

**Comment by brunobesson** [comment]
I understand it may be tricky, maybe impossible to avoid duplicating things. Still, I had to ask 🙂

**Comment by flob38** [comment]
I have no time until tuesday, but I will try something next week.

Le ven. 19 avr. 2019 09:18, Bruno Besson <notifications@github.com> a
écrit :

**Comment by cbeauchesne** [comment]
I'm not a fan of duplication : it's a path that leed us to dam heavy UI. I'd prefer to stick to a conservative way of doing thing, even if the price is sometimes to keep not perfect UI.

I've tried to find a solution last month, but the solution I saw was not the good one : I tried to use css `order` property. But to do this, I must put all box in a flex flow, with direction column. But, the blocking was that it's not possible to control the position of a new column explicitly without knowing the height of each elements.

As now, I do not have any idea of the good solution. Maybe a javascript solution that moves the block ?

**Comment by flob38** [comment]
Duplication is not a good idea. I will try something else more cleaner about the code.

**Pull request closed without merging**
