### PR TITLE
Add chinese translations

### PR DESCRIPTION
**Pull request by cbeauchesne**
Thank's to Min He, here is the first try of chinese translation for the interface. Some points to keep in mind : 

* it's **only** the interface. The content is not translated. Hopping there is some audience for Chinese to see chinese for the content also.
* When a content is loaded, and if nothing is explicitly asked (the `&l=<lang>` in url), we use the interface langage as  lang. As we do not have Chinese, I use english, assuming that it's the lang which most likely understood by chinese speaking people.

Now, the goal of this PR is testing the rendering. No need to point some missing translation (and actually, only 10% has be done), but checking that chinese character is ok, as I presume that it won't be as easy as a latin-based lang.

### CODE REVIEW

**Comment by cbeauchesne** [comment]
And here is the test version : https://c2corg.github.io/c2c_ui/chinese-translation/#/

**Comment by hemind** [comment]
If I translate more texts, what should I do in order to see the translated text in the test version?

**Comment by cbeauchesne** [comment]
Just send me a mail (it's not automatic)

**Comment by hemind** [comment]
Thanks. I see.

**Comment by hemind** [comment]
I have translated more texts. Please update the test version. Thanks.

**Comment by cbeauchesne** [comment]
> I have translated more texts. Please update the test version. Thanks.

@hemind done !

**Comment by cbeauchesne** [comment]
@hemind , updated with new translated strings

**Comment by hemind** [comment]
@cbeauchesne Thanks. Now I am translating the strings left and checking the translated strings.

**Comment by hemind** [comment]
@cbeauchesne Please update it again. Thanks.

**Comment by cbeauchesne** [comment]
@hemind done

**Comment by hemind** [comment]
Please update again. Now all the language drop-down lists do not contain Chinese. Could you please also add Chinese? Then I can test adding outing, route, waypoint, etc.

**Comment by cbeauchesne** [comment]
> Now all the language drop-down lists do not contain Chinese. Could you please also add Chinese? Then I can test adding outing, route, waypoint, etc.

You are speaking about this dropdwon ? 

https://c2corg.github.io/c2c_ui/chinese-translation/#/routes/add/zh_CN

image

**Comment by hemind** [comment]
Yes, you are right.

**Comment by cbeauchesne** [comment]
This dropdown controls the lang of the **content**. We are translating the **interface**, which is different.

The content itself will ask another changes on c2corg/v6_api, but also a discussion with camptocamp board : if the interface can be translated without any concern, it's not the same for the content, due to the nature of the site. As it's collaborative, we need to be ensure  that we'll have motivated moderators to handle all issues that come with a wiki.

For now, let's finish the interface. Then, we'll discuss about the next step with the camptocamp board.

**Comment by hemind** [comment]
Thank you for the explanation! I am going to finish the translation and check all of them in few days.

**Comment by cbeauchesne** [comment]
@hemind updated with the latest translations

**Comment by hemind** [comment]
Hello, now I have checked all the translated strings. But there are still 7 strings which I can not find in the c2c webpage, So I can not translate them. Could you please help me to find them? Or maybe we can just leave them there and maybe one day I can find them after I use the Chinese version more times.

**Comment by cbeauchesne** [comment]
* Child => https://www.camptocamp.org/associations-history?d=37355
* Parent => https://www.camptocamp.org/associations-history?d=37355 
* Dispositions => 
  * https://www.camptocamp.org/routes/46038/fr/petit-combin-couloir-w-par-le-glacier-pendant
  * on the map, click on a yellow area, it's a area flagged as protected because of environment protections
* Of => it's in the sentence "1-30 of 200 results", it's may be one of the limit of the actual system...
* scale => https://www.camptocamp.org/maps/250182/it/dora-baltea-canavesana-valchiusella-valle-sacra
* timing => https://www.camptocamp.org/outings/1198634/fr/sommet-de-la-tour-perret-tour-anti-horaire (it's a paragraph title)
* Wide and constant => 
  * arf, it sems there is a bug, the window where this strinigh is is not accessible.
  * it means, in a context of a ski, a area that is quite easy because it's wide and slope is constant. The opposite is a narrow couloir with very changing angles.

**Comment by hemind** [comment]
Thank you for the detailed explanation. Now I have finished all the translation. There maybe some strings which have not been translated very accurately. But this is the best version I can get currently, and maybe I can improve it gradually in the future. What is the next step?

**Comment by cbeauchesne** [comment]
So great! You did an amazing job! thank you a lot @hemind 

> maybe I can improve it gradually in the future

Sure, feel free to make any improvement on transifex and ping me to add them. And also, sometimes, new strings can be added, so there is some maintenance to make, keep a eye on the project.

> Next step : 

* I will prepare a release.
* And we'll discuss about the agenda for adding Chinese as a content langage. We currently having our annual meeting (camptocamp is a non-lucrative association, like [wikimedia](https://www.wikimedia.org/) ), when we have a topic about this specific point. The point that will be discussed will be the requirements that will allow this change. Spoiler, it will be mainly the difficulty of the technical change on the API, and the availability of a moderator team (as we can't have a some content without moderation). I will keep you updated of every step.

**Comment by hemind** [comment]
@cbeauchesne It's my pleasure. Thank you very much for helping me with the translation.

What are the requirements and responsibilities for a moderator? I would like to be a moderator if I meet the requirements.

And recently I plan to add some climbing materials of China in English first. If later the chinese version is ready then I can add the corresponding materials in Chinese.

**Comment by cbeauchesne** [comment]
@hemind, the new version of the UI is in prod :tada: 

Small glitch, as the chinese is not yet known by the API, the langage preference is saved only locally. If you change your browser, even if you connect to an account where you have set chinese as preferred langage, you'll have to re-switch.

> What are the requirements and responsibilities for a moderator? I would like to be a moderator if I meet the requirements.
>
> And recently I plan to add some climbing materials of China in English first. If later the chinese version is ready then I can add the corresponding materials in Chinese.

* Requirements : being motivated, and knowledge about how camptocamp works.
* Responsabilities : follow changes made on the wiki, and remove those who are not compliant with c2c rules. 

Not a big deal, it's mainly being present. I'll transfer your will to being moderator, and try to get back to you with the next step asap.

Waiting for this, feel free to continue contributing in english, and please ask any question on english forum : https://forum.camptocamp.org/c/english/news-events The more you'll understand specifities of c2c, the easier it will be.

Very glad to see your motivation !

**Comment by AntoineMarnat** [comment]
Hello @hemind !
Thank you for your amazing translation work. As @cbeauchesne told you, we have our annual meeting at the moment, and among other questions we discuss the way we should add a language. It is something new (all other languages are their from the start), and we have to decide our rules: the main problem is that we need moderators (at least to erase illegal content).

It is great if you want to be a moderator. We usualy choose moderators by looking at their contributions: we check that master the rules of Topoguide and are trustworthy. Unfortunately, the rules are [only written in french](https://www.camptocamp.org/articles/426084/fr/regles-du-topoguide) at the moment. I can translate them into english soon. What I suggest, is that you start contributing in english, and we exchange per PM if you have questions and if I have some comments/suggestions. The rules are not that complicated, especially for you that was not affraid by Transifex and Github.

Anyway, I am very happy to see your motivation !

**Comment by cbeauchesne** [comment]
> we exchange per PM if you have questions and if I have some comments/suggestions

Small detail, Antoine's name on forum is [AntoineM](https://forum.camptocamp.org/u/antoinem/summary). Mine is [CharlesB](https://forum.camptocamp.org/u/charlesb/summary) :)

**Comment by hemind** [comment]
@cbeauchesne It is so great to see the Chinese version UI. Can't wait to add more climbing information of China. Hope to discuss more with you in the forum :)

**Comment by hemind** [comment]
@AntoineMarnat Thank you for considering to add Chinese as an content language. No problem. I will continue to contribute in English. For the rules, before you give the translation, I can also read it roughly through google translator.

**Comment by hemind** [comment]
Hi @cbeauchesne !

Recently I have updated some translations and also finished some new ones. Please update the Chinese UI of our website. Thanks a lot.

**Comment by cbeauchesne** [comment]
Hi @hemind,

We merged few days ago a PR that is not compatible with the actual API, so we need to update the API before. I do not have a estimated time for this, but it'll be around before mid of June. 

Waiting for this, you can use demo deploy of master on https://c2corg.github.io/c2c_ui/master for checking purpose > the part not compatible won't work, obviously, but it's only on /xreports pages and sub pages, so you can check most of your translations.

**Comment by hemind** [comment]
@cbeauchesne Great! This is what I want. Thanks.

**Pull request merged**
