### PR TITLE
Update polyline color: add border around yellow

### PR DESCRIPTION
**Pull request by brunobesson**

### CODE REVIEW

**Comment by asaunier** [comment]
Attach perhaps a screen capture?

**Comment by brunobesson** [comment]
Or many, as there are sevaral map backgrounds

Because IGN layer is not working (lazy to get a valid key), I cheated a little bit.

There are some case when the route follows a somehow orange road. But it's still no worse than the yellow line IMHO.

image
image
image
image
image
image

**Comment by asaunier** [comment]
Thanks :)

The new color looks nice to me, but I wonder if yellow is not more visible?
In the example with the swisstopo baselayer around Grand-Saint-Bernard, the track and the road have very similar colors, don't you think?

**Comment by lbesson** [comment]
Isn't openlayer able to "outline" the lines. 
A long time ago, in another project I think we were doing that. (maybe by simply drawing two lines, the one behind being a little bit larger, in the rendering stuff for openlayers)

**Comment by lbesson** [comment]
Something like https://stackoverflow.com/questions/62512673/openlayers-how-to-add-a-colored-border-around-a-line-features

**Comment by brunobesson** [comment]
Nice proposal! I have made some tests with a yellow line and a grey outline, hich render pretty well (at leat, better than single yellow).

Some updated screenshots:
image
image
image
image
image

**Review by ataraxido — CHANGES_REQUESTED** [review]
Code okay but PR title no longer "valid"

**Review by ataraxido — APPROVED** [review]
Code okay but PR title no longer "valid"

**Pull request merged**
