### PR TITLE
Respecter c'est protéger

### PR DESCRIPTION
**Pull request by brunobesson**
Rebasing was too much of a mess

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Good for me

**Comment by cbeauchesne** [comment]
Note, I've added your rules for eslint, it makes your build fail ;) 

Run a simple `npm run lint` will fix everything.

**Comment by brunobesson** [comment]
Yeah, I just haven't found a plugin yet to use eslint properly in `.vue` files... Would you agree to abandon them? 🙂

**Comment by brunobesson** [comment]
OK, it's merged. You said something about i18n?

**Comment by cbeauchesne** [comment]
No, I was just updating my version of .pot file, but I will merge your modif in my branch

**Comment by cbeauchesne** [comment]
> Yeah, I just haven't found a plugin yet to use eslint properly in `.vue` files... Would you agree to abandon them?

God, no :D 

Have your seen this : https://github.com/c2corg/c2c_ui/blob/master/docs/development-environment.md#editor ?

**Comment by brunobesson** [comment]
Already have these extensions, but i assume i have some tweeks to do

**Pull request merged**
