### PR TITLE
style: Better display of icons on dashboard view

### PR DESCRIPTION
**Pull request by flob38**
Dashboard part of #3405

### CODE REVIEW

**Comment by flob38** [comment]
Not that pretty when screen is "wide-mobile" nor when there are more than 4 activities for 1 doc (however, 1rst April appart, I don't think we see more than 4 activities/doc very often).

**Comment by brunobesson** [comment]
image

Still needs work IMHO 🙂 

I really do not have time to work on this this week, sorry. 
May I suggest trying to put small icons below areas and keep activities on the right ?
Also, do not try to fix the separation between both blocks, let the browser handle the repartition.

**Comment by brunobesson** [comment]
> You're on the feed view

My bad! Still, event on wide screens, there is a problem IMHO with more than 2 activities (I agree, this is quite exceptional). On mobile, the current solution doesn't look that nice either with 2 activities IMHO.

image
image

Have there been discussion on the matter on the forum? I couldn't follow.

**Comment by flob38** [comment]
No real discussion on the forum for those little fixes.
On mobile, the problem shows when title is too long, or when there are a lot of activities. That why I decided to have only 2 activity icons on the same line.
Maybe it should be better to have activity icons and outing icons on another line than the title, on mobile ?

**Comment by flob38** [comment]
Discussion within CA : https://forum.camptocamp.org/t/nouvelle-page-daccueil-version-tableau-de-bord/315091
Ok for this design

**Pull request merged**
