### PR TITLE
Start date selector available in general outings filters

### PR DESCRIPTION
**Pull request by ataraxido**
It's my first commit in the project, please be tolerant :)

In my local diff I didn't have the "white blanks" issues within json, did I do something wrong or is it a automated upgrade of the file ?

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Hi @ataraxido 

> It's my first commit in the project, please be tolerant :)

We are tolerant, even with the 1000th commit :)

> In my local diff I didn't have the "white blanks" issues within json, did I do something wrong or is it a automated upgrade of the file ?

You may have configured your diff tool to ignore whitespace (it's the case on my VS code). And you probably have used a prettier tool to autoformat your files. Actually, we did not precised what should be the JSON format in our `.prettierrc` file, and `npm run lint` ignores JSON files. Two things I need to fix.

For this PR, in order to make the diff readable, can you just start back from the original files, and redo your changes without reformatting anything? Sorry for the rework!

**Comment by ataraxido** [comment]
Actually I used the shell git diff so white spaces shouldn't be ignored, I'm surprised.

I'll try to do the change need right now.

**Comment by cbeauchesne** [comment]
Strange. AFAIK, there is nothing that modify what's commited. @brunobesson may not a little bit more on that subject

**Comment by ataraxido** [comment]
@cbeauchesne after some investigations it's done by the pre-commit hook (step "Fixing up ...")

husky > pre-commit (node v10.19.0)
🔍  Finding changed files since git revision b2a6a903.
🎯  Found 1 changed file.
✍️  Fixing up src/js/constants/documentsProperties.json.
✅  Everything is awesome!

**Comment by cbeauchesne** [comment]
Goo catch. BTW, it's weird, I can't find where the JSON format is specified in the source.

BTW, you can simply remove this lines in `package.json` (and do not commit it) before doing your commit.

**Comment by ataraxido** [comment]
@cbeauchesne maybe I didn't understand what you meant but removing husky/prettier from package.json doesn't change anything :/

**Comment by cbeauchesne** [comment]
Never mind, forget about this, I'll do the review like this.

**Comment by ataraxido** [comment]
I just understood, doing what's needed.

**Comment by cbeauchesne** [comment]
Ok , checking locally

**Comment by cbeauchesne** [comment]
BTW, thank you for finding where the "issue" about formatting. I think I've understood what @brunobesson intented to do and precised it in our wiki : https://github.com/c2corg/c2c_ui/wiki/good-to-knows/_compare/ffac58942665ea374c284b541ccc72cf4332bac5...91570987aeff20fdb98b09e5783f75f28d337497

I will push a commit after this PR to `prettier` all files (I can't understand why those JSON files was sipped though...)

**Comment by brunobesson** [comment]
Sorry I wasn't able to answer before.

As you stated in the documentation, these are 2 different things:
* `prettier` tool is about code formatting and styling. A pre-commit hook is driven by `husky` and `pretty-quick` to ensure it is run on each modified file. But most of the time you have also configured your IDE to format on save with prettier.
* Linting is done through `eslint`. This tool does static code analysis, reporting both coding styling and putative errors. It could also handle some code formatting, but we have disabled these rules in order not to clash with prettier.

**Comment by cbeauchesne** [comment]
Released !

**Pull request merged**
