### PR TITLE
Support webp and avif format via <picture>

### PR DESCRIPTION
**Pull request by brunobesson**
The goal is to replace \ by \<picture> each time we refer to a thumbnail (SI, MI, BI) of a c2c image, and propose webp and avif format to the browser.

A timestamp and start id are defined in config, so that we don't try to get avif or webp if they are not generated.
Ultimately we should have a script generating all missing avif and webp thumbnails and get rid of this limitation.

There are a few places to be checked (currently slideshows are often broken):

- [x] AssociationImageLink
- [x] Gallery - often a display / slide issue until we resize a bit the window with chrome ??
- [x] Markdown
- [x] ImageViewer : error when zooming in / out
- [x] ImageCards
- [x] SophiePictureContestView
- [x] DiffView
- [x] ImageEditionView

(All of the above only tested on chrome desktop and firefox desktop at the moment)

### CODE REVIEW

**Comment by brunobesson** [comment]
Last found bugs should be fixed now by patching swiper 😒

@lbesson could you review and test?

**Comment by lbesson** [comment]
@brunobesson I changed the timeout from 100 to 0 and provided additional comment.
Can you please (again) test on your side and if happy, merge?

**Review by lbesson — APPROVED** [review]

**Comment by brunobesson** [comment]
If the problem resides only in the gallery spacing between images, then yes it seems to b fine.

**Comment by lbesson** [comment]
hum, I should have squashed

**Pull request merged**
