### PR TITLE
feat(statistics): fix NaN when there is no outing yet

### PR DESCRIPTION
**Pull request by mathieudutour**
Saw this 
Screenshot 2022-10-24 at 14 48 31
and decided to fix it directly

### CODE REVIEW

**Comment by brunobesson** [comment]
Thanks for your PR @mathieudutour !

If a user has no outings, the case is not handled very well yet, I agree.
However, I am not sure 0% is he correct choice. Should'n it be 100% instead?
Also, we could avoid displaying empty graph and print a small text instead (but this could be another work).

What do you think?

**Comment by brunobesson** [comment]
> True

Would you volunteer to continue on this issue (i.e. hide empty graphs)?

**Comment by mathieudutour** [comment]
Happy to yes, will do so in another PR

**Comment by mathieudutour** [comment]
Do we have an existing screen with an empty state (so that I don't reinvent the wheel)?

**Comment by brunobesson** [comment]
> Do we have an existing screen with an empty state (so that I don't reinvent the wheel)?

I cannot think on any case for this, except maye empy results in a table:
image

Anyway, I do not think of something very complicated: a simple paragraph with some style saying e.g. `No outings yet. Share your achievements and feedback with the camptocamp community to have some stats!`

**Pull request merged**
