### PR TITLE
Update filling color of activities svg

### PR DESCRIPTION
**Pull request by flob38**
Change filling color to match other activities

### CODE REVIEW

**Review by brunobesson — COMMENTED** [review]
Where does the new color come from?
c2c orange is `#f93`...

Maybe the old color is bad too... 🙁

**Comment by flob38** [comment]
> Anyway, didn't dig the subject, but the SVG color is usually replaced through CSS isn't it?

Yes, but someone who would use it for another support (like poster :) ) would have the wrong color.

Ok so we have to change all svg for they are filling with #ffaa45

**Comment by cbeauchesne** [comment]
Confirm, it's #f93: https://forum.camptocamp.org/t/projet-ui-quel-est-le-orange-c2c/238878/10

**Comment by flob38** [comment]
That why we need a summary : https://www.camptocamp.org/articles/1366655/fr/charte-graphique-camptocamp-association

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
