### PR TITLE
Add slovenian (sl) for UI

### PR DESCRIPTION
**Pull request by brunobesson**
Also fix one missing translation key for chinese

Replaces #2327

### CODE REVIEW

**Comment by BorutK** [comment]
Hello, 

Thanks for this development. 

I thought I might mention that thanks to the demo I made some (minor) changes on Transifex. I guess they will be taken into account when everything is ready for the next step. 

Borut

**Comment by brunobesson** [comment]
Exactly, there are automatic pull requests built when transifex translations are being edited.

**Comment by AntoineMarnat** [comment]
Indeed, see the automatic commit : https://github.com/c2corg/c2c_ui/commit/4bd162821476527522769c6aab4579b5fc6b27cb#diff-fd32b911f7174bc80e3409222b82b08527884a22362942e27e8f9c78d33962d1

**Comment by BorutK** [comment]
Thanks!
________________________________

**Comment by brunobesson** [comment]
Fixes #2334

**Pull request merged**
