### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by ataraxido**
For https://github.com/c2corg/c2c_ui/issues/1449

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Can you redo the PR by using directly the c2corg repo (not your fork) ? 

The demo app is spawned by our CIi, and it does not trigger for the PR coming from a fork (security reasons)

**Comment by ataraxido** [comment]
@cbeauchesne I don't know how to do that sorry ( I have been working on Bitbucket for years, I'm not used to Github ).
Because my branch is on my fork and not on the c2c repo.

**Comment by brunobesson** [comment]
@cbeauchesne he won't have right to push to the repo and do a PE.

**Comment by ataraxido** [comment]
I already cloned the "main" repo, then added my fork.
But my branch has been created and push on my fork and not on the "main" repo so I don't see how I could then push this branch to the "main" repo ( but I'm not a git guru ).

**Comment by cbeauchesne** [comment]
@brunobesson I wanted to have the demo app to be able to show it to users.

The good process here would be to be able to trigger the `ci.yml::github-pages` job manually, but I confess not having searching how to do that.

**Pull request closed without merging**
