### PR TITLE
Add chineese for moment.js

### PR DESCRIPTION
**Pull request by cbeauchesne**
We'll need an approval from He-min :)

### CODE REVIEW

**Comment by brunobesson** [comment]
>We'll need an approval from He-min :)

Why? He won't refuse a correct translation of the interface, will he?

Other than that, have you tested your PR works? The locale for moment is `zh-cn` while for i18n it is `zh_CN`.

**Comment by cbeauchesne** [comment]
Yep it works: 

image

I just want to check with him that the message is well translated.

**Comment by brunobesson** [comment]
OK, good.

What about this however? (not related to this PR). I thought it was 100% translated?

image

**Comment by cbeauchesne** [comment]
Just an issue on vue reactive values, need a refresh : 

image

**Comment by hemind** [comment]
Hi Charles, I have found the footer is still in english. Here "8 minutes ago".

image

**Comment by cbeauchesne** [comment]
@hemind, did you check on this URL ? 

https://c2corg.github.io/c2c_ui/moment-chineese/#/

**Comment by hemind** [comment]
@cbeauchesne 
Before I checked this url https://www.camptocamp.org/.

Now I checked the url below, and it is translated correctly!
https://c2corg.github.io/c2c_ui/moment-chineese/#/

**Comment by hemind** [comment]
@cbeauchesne Another comment about outing date, "Sunday 1st September 2019" should be "2019年 9月 1日 星期日" in Chinese. Now it is "星期日 1日 九月 2019". See pics below.

Could you please change it to the correct order, and also add string "年" which means "year"?

"九月" has the same meaning with "9月" which means September, but "9月" is better so I have modified the translation in transifex. 

image

image

**Comment by cbeauchesne** [comment]
is this ok ? 

image

**Comment by hemind** [comment]
@cbeauchesne Perfect! Thanks.

**Pull request merged**
